### PR TITLE
fix(package.json): don't define minichain dependency in both deps and…

### LINKED ISSUE #2: do not have same dependency in dependencies and peerDependencies
detail https://github.com/npm/npm/issues/6506#issuecomment-63883598

### PR DESCRIPTION
**Pull request by IgorMinar**
… devDeps

Fixes #2

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Oh, I was about to open a PR for this but it looks like Igor was faster :-) 
@IgorMinar I wonder why we need to do this fix for `minichain` but not for `ministyle`? This is the same situation / pb, no?

**Comment by IgorMinar** [comment]
@pkozlowski-opensource good point. in tsd's case the ministyle dep is not a problem because it is required by tsd itself, so the peerdependency is actually there.

**Comment by IgorMinar** [comment]
so, for the purposes of solving our particular problem, I don't think we care about ministyle.

**Comment by alexeagle** [comment]
@IgorMinar that means our backup plan is just to add an explicit dep from tsd to minichain, we don't need to fork minitable too.

**Comment by Bartvds** [comment]
Sorry for the wait guys, life went another way. Lemme get back on the horse and I'll get the things sorted out.

**Comment by alexeagle** [comment]
Thank you!

**Comment by Bartvds** [comment]
This is on npm as 0.0.4.

Now we hustle a new TSD release as apparently [I pinned only this module to an exact version..](https://github.com/DefinitelyTyped/tsd/blob/dev/next/package.json#L66) :confused:

**Comment by Bartvds** [comment]
I just realized I only merged the PR but not appreciated the discussion. So let me know if you also need the other peerDependency removed.

**Comment by IgorMinar** [comment]
it's weird that ministyle is both `dependency` and `peerDependency`. It's not clear what that means, but npm 2.x is currently happy. npm 3.x might break this again though, so it might be good to revisit what you actually need here. do you need ministyle to be provided by whoever is including minitable or do you just want npm to provide it to you as your own dependency?

**Comment by IgorMinar** [comment]
thanks for merging the PR though! let's get a TSD release out so that this major PITA is over.

**Pull request merged**
